# Generated by Django 6.0.3 on 2026-04-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(blank=True, max_length=250, null=True)),
                ('discription', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, max_length=250, null=True)),
                ('contents', models.ManyToManyField(blank=True, related_name='content_images', to='admin_dashboard.files')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_heading', models.CharField(max_length=250)),
                ('discription', models.TextField(blank=True)),
                ('images', models.ManyToManyField(blank=True, related_name='features_images', to='admin_dashboard.imagesfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('discription', models.TextField()),
                ('value_max', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('value_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('features', models.ManyToManyField(blank=True, related_name='features', to='admin_dashboard.features')),
            ],
        ),
    ]
